### ISSUE TITLE
Feature request: configurable prometheus queries

### ISSUE THREAD

**Issue by djfinnoy** [robusta-dev/krr#138]
We use  [kube-eagle](https://medium.com/@martin.schneppenheim/utilizing-and-monitoring-kubernetes-cluster-resources-more-effectively-using-this-tool-df4c68ec2053) and victoria metrics.

Right now, I have to set up a scrape job from cadvisor solely dedicated to krr:

```
  # These metrics are required by https://github.com/robusta-dev/krr
  - job_name: kubelet
    scheme: https
    tls_config:
      ca_file: /var/run/secrets/kubernetes.io/serviceaccount/ca.crt
      insecure_skip_verify: true
    bearer_token_file: /var/run/secrets/kubernetes.io/serviceaccount/token
    kubernetes_sd_configs:
      - role: node
    relabel_configs:
      - action: labelmap
        regex: __meta_kubernetes_node_label_(.+)
      - target_label: __address__
        replacement: kubernetes.default.svc:443
      - source_labels: [__meta_kubernetes_node_name]
        regex: (.+)
        target_label: __metrics_path__
        replacement: /api/v1/nodes/$1/proxy/metrics/cadvisor
    metric_relabel_configs:
      # We only need the following metrics because they are needed by robusta-dev/krr, everything else we get from kube-eagle
      - action: keep
        if: '{__name__=~"(container_cpu_usage_seconds_total|container_memory_working_set_bytes)"}'
```

I think it would be an improvement if one could overwrite the [queries mentioned in the docs](https://github.com/robusta-dev/krr#metrics-gathering) to whatever fits the local setup.
Let users figure out the equivalent queries for tools like kube-eagle.
