### ISSUE TITLE
Tool is showing `unset` for all resources for most namespaces

### ISSUE THREAD

**Issue by bmaupin** [robusta-dev/krr#366]
I'm not a kubernetes expert at all, so maybe we're doing this incorrectly. We have the following LimitRange set by default for most of our namespaces:
```yaml
  - kind: LimitRange
    apiVersion: v1
    metadata:
      name: "core-resource-limits"
      namespace: ...
    spec:
      limits:
        - type: "Container"
          max:
            memory: "1Gi"
          defaultRequest:
            cpu: "5m"
            memory: "128Mi"
```

The deployed pods have resources accordingly set, e.g.

```yaml
  containers:
    - resources:
        limits:
          memory: 1Gi
        requests:
          cpu: 5m
          memory: 128Mi
```

However, when we run this tool, it says "unset" for CPU/memory requests/limits.

![image](https://github.com/user-attachments/assets/b9fe8d61-6176-4ccc-ac18-7b137c88d7e4)

For comparison, I found another namespace where only one of the containers showed unset:

![image](https://github.com/user-attachments/assets/f36b6af6-48b2-4ade-be6d-bb88f15b54d9)

The only difference I can tell between the second example and the ones that aren't working is that the ones that are showing "unset" for all values don't have CPU limits set, as per https://home.robusta.dev/blog/stop-using-cpu-limits

The closest issue I found was this one: https://github.com/robusta-dev/krr/issues/200

But we're not using AWS and we're not getting any warnings. We just get messages like this for the projects that are showing unset:

```
INFO     Calculated recommendations for Deployment appdev-ci-pipeline-development/development/auto-deploy-app (using 4 metrics)
```
 
Thanks!
