### ISSUE TITLE
Does not work with a proxy

### ISSUE THREAD

**Issue by magnusboman** [robusta-dev/krr#44]
I need a proxy to get to our kubernetes environments. 
The proxy is specified in kubeconfig but it seems krr aren't using it.
I also tried to set an http{s}_proxy env variable but that didn't work either.

Using krr v1.0.0.

**Comment by LeaveMyYard** [comment]
Hey, @magnusboman 

Could you share an example on how your proxy is configured in kubeconfig?

**Comment by magnusboman** [comment]
@LeaveMyYard :
```
clusters:
    - cluster:
        certificate-authority-data: xxx
        proxy-url: http://admin:password@127.0.0.1:8118
        server: https://xxx
      name: name
```
